### PR TITLE
Feature/rugged

### LINKED ISSUE #185: Change tracking - integrate Git?
We need a way to track who makes changes to Terms and what those changes are.

One option may be to integrate Git into the app, where a repo keeps a copy of the data and tracks changes that way. 
This gem should help with Git: https://github.com/libgit2/rugged  
So add a hook on each save to make a commit in Git as the user doing the save. This could then be pushed to GitHub as a backup. Once we build out Review/Approval queues, those could be handled in branches. We could also then pull in commit history from the Git repo and display that on Term pages, which may fulfill #183 . I don't envision needing to make changes directly to the Git repo, as it would be hard to sync back to the app.

Another option might be to use Changeset vocab and add triples to the record every time a change is made.
http://vocab.org/changeset/schema#ChangeSet
This is used lightly by LC at id.loc.gov

### PR DESCRIPTION
**Pull request by lsat12357**
fixes #185 

it's a start.

### CODE REVIEW

**Comment by straleyb** [comment]
For anyone poking around with this branch you will need CMAKE to install rugged. 
```
brew install cmake
```

**Comment by lsat12357** [comment]
oh and it expects a directory called git_dev with at least an initial commit.

**Comment by straleyb** [comment]
Could you supply a few commands to build that directory and do an initial commit? Im familiarizing myself with the code and having git in the application.

**Comment by lsat12357** [comment]
mkdir git_dev
cd git_dev
git init
touch first
git add first
git commit -m 'initial commit'

**Pull request closed without merging**
