### PR TITLE
Remove .rspec from repository

### PR DESCRIPTION
**Pull request by jechols**
Allows devs to individually customize rspec flags - to fail tests
quickly, skip profile data, enable full backtrace, etc.

### CODE REVIEW

**Comment by jechols** [comment]
@OregonDigital/developers - any objections to pulling .rspec out of git and allowing us to individually override flags?

**Comment by terrellt** [comment]
@jechols Huh, does .rspec override passed flags?

**Comment by jechols** [comment]
I believe it goes something like flags -> .rspec -> spec_helper settings.

I'm of the opinion that settings we want as defaults should be in spec_helper, as those always have to be in the repo.  Then devs can customize their personal defaults, and override with flags for specific situations.

**Comment by terrellt** [comment]
Can we turn on coloring from the spec_helper then?

**Comment by jechols** [comment]
We can!

**Comment by terrellt** [comment]
Alright, now I'm on board. :+1:

**Comment by terrellt** [comment]
@wickr @lsat12357 @zhang4952 ?

**Comment by wickr** [comment]
Fine with me.

**Pull request merged**
