### PR TITLE
Add listing of terms within a Vocabulary.

### PR DESCRIPTION
**Pull request by terrellt**

### CODE REVIEW

**Comment by terrellt** [comment]
@jechols @wickr @lsat12357 @zhang4952 Can we talk about this PR? Thoughts?

**Comment by jechols** [comment]
The factory feels like it should have been a different PR to me (or at least a separate commit in this one), but I wouldn't hold up this PR over it.  I say we merge.

**Comment by terrellt** [comment]
@jechols That's interesting - I wrote it up that way because otherwise I would have had to inline the responsibility of decoration. Why's that a different PR?

**Comment by jechols** [comment]
Seems like a different feature to me.  I think a separate commit would have made sense, too, but you know how I am with committing very small chunks :)

I don't think it's worth discussion, it's probably just my own bias.  Unless there's a *real* problem, I still vote we merge.

**Pull request merged**
