### PR TITLE
Feature/add cache button

### LINKED ISSUE #458: Button for admins to clear cached files (HTML, nt, jsonld) for Term, Vocabulary or Predicate
Occasionally certain changes happen and the cached HTML (and nt and jsonld) gets stuck, requiring logging in to the server and deleting the files, forcing a new version to be created. 

Add a button on a Term/Predicate/Vocabulary show page to force removing the HTML and reload, titled "Clear Cached Files"

### PR DESCRIPTION
**Pull request by lsat12357**
fixes #458

### CODE REVIEW

**Comment by lsat12357** [comment]
so it turns out I couldn't just launch into clearing the cache directly from the show page

**Comment by lsat12357** [comment]
termshow

**Comment by lsat12357** [comment]
termcache

**Comment by lsat12357** [comment]
vocabcache

**Comment by straleyb** [comment]
Looks good here. @wickr ?

**Pull request merged**
