### PR TITLE
Fix/cache nts

### LINKED ISSUE #442: When review is complete for a Term, create .nt and .jsonld files
Right now the .nt and .jsonld files are created when requested (clicked on link in web UI) but a server-based fetch does not create the files and succeed. We should just create the files automatically when the Term is successfully reviewed, instead of waiting for a request to come in.

May be related to #388

### PR DESCRIPTION
**Pull request by lsat12357**
fixes #442

### CODE REVIEW

**Comment by lsat12357** [comment]
capture1

**Comment by lsat12357** [comment]
capture2

**Comment by straleyb** [comment]
Looks good but could we do something like
```
services/controlledvocabularymanager/preload_cache.rb
```
Other than that looks good on my end.

**Comment by wickr** [comment]
Yeah can you move that to a service? Otherwise it looks great.

**Comment by lsat12357** [comment]
hm is this ok? all of the services were just there at that level

**Pull request merged**
