### PR TITLE
Feature/enable uri

### LINKED ISSUE #305: Putting a URI in a form field saves it as a string
Should actually save it as a URI

### LINKED ISSUE #307: If a URI exists in a property, when editing the Term it shows as 'default'
The 'default' label is displayed for a form field that is a URI. 'default' then gets saved as the value.

Related to #158

### PR DESCRIPTION
**Pull request by luisgreg99**
fixes #305 
fixes #307

### CODE REVIEW

**Comment by wickr** [comment]
This chain of methods (and anything similar that's in most of the views changes) seems wrong, there seems to be too many levels:
```
v.rdf_label.first.rdf_label.first
```

**Comment by luisgreg99** [comment]
@wickr: Those methods are currently being used on the vocabularies and predicates index pages (for example) just to display the titles properly. This is only rendered when there is only one URI in the title, so instead of displaying `default` in the title column, it would display the first URI value associated with the first title field. I came across this special case when I was testing URIs specifically in the title and label fields, do you think we should allow URIs in the title field in particular?

**Comment by wickr** [comment]
@luisgreg99 ok, I follow. But I would expect Title and Label to be literals, not ever be just a RDF::URI.

That should mean you don't need most of the view changes.

**Comment by luisgreg99** [comment]
@wickr: ok sounds good, that makes it simpler. I will remove those views changes.

**Pull request merged**
