### PR TITLE
Add title and publisher to Vocabulary

### PR DESCRIPTION
**Pull request by jechols**
Adds Vocabulary properties we use in our JSONLD

### CODE REVIEW

**Comment by terrellt** [comment]
So I think this is the right place for this, but these fields likely won't show up on the terms show page without some edits later. Probably a different PR?

**Comment by jechols** [comment]
That's a good question. I think we need this stuff to show up.  May not be a separate PR, but it begs a bigger question: what about the form?

**Comment by terrellt** [comment]
I think it would show up in the new vocab form if we worked a little bit on how it chooses what fields to display.

**Comment by jechols** [comment]
Oh, it's not hard - but do we want all the fields there?  A subset?  For OD terms, we don't seem to use comment or label on the vocabularies themselves, for instance.  I'm not sure who answers a question like this, but it is definitely a bigger decision than me, I think.

In any case, we know the properties need to be there, so maybe we merge this and I go file a ticket to deal with the form/view...?

**Comment by terrellt** [comment]
:+1:

**Pull request merged**
